ArithmeticException occurs-

public class ArithmeticExceptionTest {
   public static void main(String[] args) {
      int a = 0, b = 10;
      int c = b/a;
      System.out.println("Value of c is : "+ c);
   }
}


Handling of ArithmeticException as follows - 

   class ArithmeticExceptionTest {
   public static void main(String[] args) {
      int a = 0, b = 10 ;
      int c = 0;
      try {

         c = b/a;

      } catch (ArithmeticException e) {
          // e.printStackTrace();
          System.out.println("Error occurs");

      }
      finally{ //by default execute...
	  System.out.println("Hello");
      }		  
   }
}